# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_oferta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oferta',
        ),
    ]
